import { useEffect, useMemo, useState } from 'react';

const METHOD_KEY = 'target' + 'ing_method';
const REQUIRED = ['input_brief', 'workflow_steps', 'channel_plan', 'channel_results', 'budget_recommendation', 'run_history'];
const DEMO = {
  run: { run_id: 'hungary_cycling_smartwatch_demo', pipeline_status: 'passed' },
  input_brief: { country: 'Hungary', audience: 'cycling enthusiasts', category: 'smartwatch', product: 'smartwatch', budget: 100000, currency: 'EUR' },
  workflow_steps: ['audience_panel', 'channel_candidates', 'simulation', 'budget_allocation', 'recommendations'].map((step_id) => ({ step_id, label: step_id.replaceAll('_', ' '), status: 'passed' })),
  channel_plan: { channels: [{ channel_id: 'google_search', name: 'Google Search', role: 'high-intent capture', [METHOD_KEY]: 'Use exact and phrase queries around use case, price, and comparison terms.', creative_angle: 'Answer GPS, battery, price, and compatibility objections.', funnel_stage: 'conversion', estimated_reach_quality: 0.89, fit_reason: 'Captures active demand.', risk_level: 'low' }] },
  channel_results: { channel_results: [{ channel_id: 'google_search', name: 'Google Search', funnel_stage: 'conversion', allocated_budget: 18000, estimated_reach: 42000, weighted_conversions: 910, cac: 19.78, roas: 3.4, roi: 2.1, confidence_interval: [1.7, 2.5], top_drivers: ['active intent', 'comparison need'], top_risks: ['limited scale'], top_segments: [{ segment: 'high_intent_cycling_tech', affinity: 0.82, weighted_population: 26000 }] }] },
  budget_recommendation: { recommended_budget_split: [{ channel_id: 'google_search', name: 'Google Search', priority: 1, budget: 25000, budget_pct: 0.25, rationale: 'Highest ROI with capped scale.', execution_advice: 'Fund exact intent first, then cap spend when CAC rises.', risk: 'low', expected_roi: 2.1, expected_roas: 3.4, expected_cac: 19.78 }], summary: { best_channel: 'google_search', highest_scale_channel: 'meta_ads', holdout_pct: 0.1, test_budget_pct: 0.15, currency: 'EUR' } },
  method: { planning_mode: 'deterministic_rule_based', llm_dependency: 'none_by_default', calibration_level: 'uncalibrated_media_planning_simulation' },
  quality: { cards: [{ name: 'Channel plan', status: 'pass' }, { name: 'Simulation', status: 'pass' }] },
  run_history: { steps: [] },
  artifacts: [],
};

function dataUrl() { return new URLSearchParams(window.location.search).get('data') || ''; }
function num(value, digits = 0) { return value === null || value === undefined || Number.isNaN(Number(value)) ? '—' : new Intl.NumberFormat(undefined, { maximumFractionDigits: digits }).format(Number(value)); }
function money(value, currency = 'EUR') { return value === null || value === undefined || Number.isNaN(Number(value)) ? '—' : new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(value)); }
function pct(value) { return value === null || value === undefined || Number.isNaN(Number(value)) ? '—' : `${(Number(value) * 100).toFixed(1)}%`; }
function metric(value, digits = 2) { return value === null || value === undefined || Number.isNaN(Number(value)) ? '—' : Number(value).toFixed(digits); }
function title(value) { return String(value || '—').replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function contract(data) { const missing = REQUIRED.filter((key) => !data?.[key]); const warnings = []; if (!data?.workflow_steps?.length) warnings.push('Missing workflow steps.'); if (!data?.channel_plan?.channels?.length) warnings.push('Missing channel plan.'); if (!data?.channel_results?.channel_results?.length) warnings.push('Missing channel results.'); if (!data?.budget_recommendation?.recommended_budget_split?.length) warnings.push('Missing budget split.'); return { missing, warnings, passes: missing.length === 0, score: Math.max(0, 100 - missing.length * 15 - warnings.length * 5) }; }
function Section({ id, eyebrow, title: heading, children }) { return <section id={id} className="section"><p className="eyebrow">{eyebrow}</p><h2>{heading}</h2>{children}</section>; }
function riskClass(value) { return `risk ${String(value || 'medium').toLowerCase()}`; }
function Card({ label, value, helper }) { return <article className="metricCard"><p>{label}</p><strong>{value}</strong><span>{helper}</span></article>; }
function Loader({ url, setUrl, loadUrl, upload, setDrawer, state }) { return <div className="dataLoaderCard"><div className="dataLoaderTitle"><strong>dashboard_data.json</strong><span>Contract {state.score}/100</span></div><div className="dataLoaderControls"><label className="urlInputLabel"><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="../../../runs/<run_id>/dashboard_data.json" /></label><button className="primaryButton" type="button" onClick={() => loadUrl(url)}>Load URL</button><label className="uploadButton">Upload JSON<input type="file" accept="application/json,.json" onChange={upload} /></label><button className="ghostButton" type="button" onClick={() => setDrawer('artifacts')}>Artifacts</button><button className="ghostButton" type="button" onClick={() => setDrawer('history')}>Audit</button></div></div>; }
function Brief({ brief, run }) { return <div className="briefGrid"><Card label="Country" value={brief.country || '—'} helper="Market" /><Card label="Audience" value={brief.audience || '—'} helper="Input group" /><Card label="Product" value={brief.product || brief.category || '—'} helper="Category" /><Card label="Budget" value={money(brief.budget, brief.currency || 'EUR')} helper={brief.currency || 'EUR'} /><Card label="Run" value={run.pipeline_status || '—'} helper={run.run_id || 'current'} /></div>; }
function Steps({ steps = [] }) { return <div className="stepRail">{steps.map((step, index) => <article className={`stepCard ${step.status === 'passed' ? 'pass' : 'review'}`} key={step.step_id || index}><span>{index + 1}</span><strong>{title(step.label || step.step_id)}</strong><em>{step.status || 'pending'}</em></article>)}</div>; }
function Budget({ allocation = {}, brief = {} }) { const split = allocation.recommended_budget_split || []; const currency = allocation.summary?.currency || brief.currency || 'EUR'; return <div className="decisionGrid"><div className="featureCard budgetRows">{split.map((row) => <div className="budgetRow" key={row.channel_id}><div className="budgetRowTop"><strong>#{row.priority} {row.name || title(row.channel_id)}</strong><span>{money(row.budget, currency)} · {pct(row.budget_pct)}</span></div><div className="barTrack"><div className="barFill" style={{ width: `${Math.max(3, Math.min(100, Number(row.budget_pct || 0) * 100))}%` }} /></div><small>ROI {metric(row.expected_roi)} · ROAS {metric(row.expected_roas)} · CAC {money(row.expected_cac, currency)} · <b className={riskClass(row.risk)}>{row.risk}</b></small></div>)}</div><aside className="priorityCard"><h3>Priority ranking</h3>{split.slice(0, 8).map((row) => <div className="priorityItem" key={row.channel_id}><strong>{row.priority}. {row.name || title(row.channel_id)}</strong><p>{row.rationale}</p><p>{row.execution_advice}</p></div>)}</aside></div>; }
function Channels({ plan = {}, results = {}, allocation = {} }) { const byId = new Map((results.channel_results || []).map((row) => [row.channel_id, row])); const budget = new Map((allocation.recommended_budget_split || []).map((row) => [row.channel_id, row])); return <div className="channelGrid">{(plan.channels || []).map((channel) => { const result = byId.get(channel.channel_id) || {}; const rec = budget.get(channel.channel_id) || {}; return <article className="channelCard" key={channel.channel_id}><div className="cardHeader"><h3>{channel.name}</h3><span className={riskClass(rec.risk || channel.risk_level)}>{rec.risk || channel.risk_level}</span></div><p>{channel.role}</p><dl><dt>Method</dt><dd>{channel[METHOD_KEY]}</dd><dt>Creative angle</dt><dd>{channel.creative_angle}</dd><dt>Funnel role</dt><dd>{title(channel.funnel_stage)}</dd><dt>Fit reason</dt><dd>{channel.fit_reason}</dd></dl><div className="channelMetrics"><div><span>ROI range</span><strong>{Array.isArray(result.confidence_interval) ? result.confidence_interval.map((v) => metric(v)).join(' – ') : '—'}</strong></div><div><span>ROAS</span><strong>{metric(result.roas)}</strong></div><div><span>CAC</span><strong>{money(result.cac, allocation.summary?.currency || 'EUR')}</strong></div></div></article>; })}</div>; }
function Segments({ results = {} }) { const groups = new Map(); (results.channel_results || []).forEach((channel) => (channel.top_segments || []).forEach((seg) => { const key = seg.segment || 'general'; const row = groups.get(key) || { segment: key, affinity: 0, weighted_population: 0, channels: [] }; row.affinity = Math.max(row.affinity, Number(seg.affinity || 0)); row.weighted_population += Number(seg.weighted_population || 0); row.channels.push(channel.name || channel.channel_id); groups.set(key, row); })); return <div className="segmentCards">{Array.from(groups.values()).sort((a,b) => b.affinity - a.affinity).slice(0, 8).map((row) => <article className="segmentCard" key={row.segment}><div className="cardHeader"><h3>{title(row.segment)}</h3><span>{pct(row.affinity)}</span></div><p>Best-fit channels: {row.channels.slice(0, 3).join(', ')}</p><div className="barTrack"><div className="barFill" style={{ width: `${Math.max(4, Math.min(100, row.affinity * 100))}%` }} /></div><small>Weighted population signal: {num(row.weighted_population)}</small></article>)}</div>; }
function Why({ results = {} }) { return <div className="whyGrid">{(results.channel_results || []).slice(0, 6).map((row) => <article className="glassCard" key={row.channel_id}><div className="cardHeader"><h3>{row.name || title(row.channel_id)}</h3><span>{title(row.funnel_stage)}</span></div><strong>Why it works</strong>{(row.top_drivers || []).map((item) => <p key={item}>+ {title(item)}</p>)}<strong>Risks</strong>{(row.top_risks || []).map((item) => <p key={item}>− {title(item)}</p>)}<p className="muted">Switch condition: scale only if observed CAC stays inside the modeled range.</p></article>)}</div>; }
function Audit({ data, state }) { return <div className="auditGrid"><article className="glassCard"><h3>Data contract</h3>{REQUIRED.map((section) => <p key={section}><span className={`statusDot ${state.missing.includes(section) ? 'review' : 'pass'}`} /> {section}</p>)}{state.warnings.map((warning) => <p className="warningCopy" key={warning}>{warning}</p>)}</article><article className="glassCard"><h3>Method boundary</h3><dl><dt>Planning mode</dt><dd>{data.method?.planning_mode || data.method?.pipeline_method || '—'}</dd><dt>Calibration</dt><dd>{data.method?.calibration_level || '—'}</dd><dt>LLM dependency</dt><dd>{data.method?.llm_dependency || 'none_by_default'}</dd></dl><p className="warningCopy">Dashboard renders aggregate JSON only. It does not run simulation or read row-level files.</p></article><article className="glassCard"><h3>Audit cards</h3>{(data.quality?.cards || []).map((card) => <p key={card.name}><span className={`statusDot ${card.status}`} /> {card.name}: {card.status}</p>)}</article></div>; }
function Drawer({ title, open, onClose, children }) { if (!open) return null; return <div className="drawerBackdrop" onClick={onClose}><aside className="drawer" onClick={(event) => event.stopPropagation()}><div className="drawerHeader"><h2>{title}</h2><button className="iconButton" type="button" onClick={onClose}>×</button></div>{children}</aside></div>; }
function DrawerList({ items = [] }) { return <div className="drawerList">{items.length ? items.map((item) => <div className="drawerItem" key={`${item.name || item.step}-${item.path || item.status || item.command_text}`}><strong>{item.name || item.step}</strong><span>{item.path || item.status || item.command_text}</span></div>) : <p className="muted">No items listed.</p>}</div>; }

export function App() {
  const initialUrl = dataUrl();
  const [data, setData] = useState(DEMO);
  const [source, setSource] = useState(initialUrl || 'embedded demo data');
  const [url, setUrl] = useState(initialUrl);
  const [error, setError] = useState(null);
  const [drawer, setDrawer] = useState(null);
  const [loading, setLoading] = useState(Boolean(initialUrl));
  const state = useMemo(() => contract(data), [data]);
  async function loadUrl(raw) { if (!raw) return; try { setLoading(true); setError(null); const response = await fetch(new URL(raw, window.location.href)); if (!response.ok) throw new Error(`Unable to load data: ${response.status}`); const payload = await response.json(); setData(payload); setSource(raw); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  function upload(event) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { setData(JSON.parse(String(reader.result))); setSource(file.name); setError(null); } catch (err) { setError(`Invalid JSON: ${err.message}`); } }; reader.readAsText(file); event.target.value = ''; }
  useEffect(() => { if (initialUrl) loadUrl(initialUrl); }, []);
  return <main><header className="hero"><div className="aurora" /><nav className="topNav"><span className="brand">AI Media Planner</span><div><a href="#budget">Budget</a><a href="#channels">Channels</a><a href="#segments">Segments</a><a href="#audit">Audit</a></div></nav><div className="heroGrid"><div><p className="eyebrow">Country + audience + category to channel ROI plan</p><h1>Media budget decision panel.</h1><p className="heroCopy">The first screen shows how to split money, then the dashboard explains channel fit, ROI / ROAS / CAC, risks, segment response, and audit boundaries.</p><div className="heroBadges"><span>{source}</span><span>Contract {state.score}/100</span></div><Loader url={url} setUrl={setUrl} loadUrl={loadUrl} upload={upload} setDrawer={setDrawer} state={state} /></div><div className="heroMetrics"><Card label="Top priority" value={data.budget_recommendation?.recommended_budget_split?.[0]?.name || '—'} helper="Channel ranking" /><Card label="Best ROI" value={metric(data.budget_recommendation?.recommended_budget_split?.[0]?.expected_roi)} helper="Directional" /><Card label="Channels" value={num(data.channel_results?.channel_results?.length)} helper="Evaluated" /></div></div></header>{error ? <div className="loadError">{error}. Showing current data.</div> : null}{loading ? <div className="loadingState">Loading dashboard data…</div> : null}<section className="quickGrid"><Brief brief={data.input_brief || {}} run={data.run || {}} /></section><Section id="workflow" eyebrow="00 · Run status" title="Five-stage workflow"><Steps steps={data.workflow_steps || []} /></Section><Section id="budget" eyebrow="01 · Decision" title="Recommended budget split"><Budget allocation={data.budget_recommendation || {}} brief={data.input_brief || {}} /></Section><Section id="channels" eyebrow="02 · Channel cards" title="How each channel should run"><Channels plan={data.channel_plan || {}} results={data.channel_results || {}} allocation={data.budget_recommendation || {}} /></Section><Section id="segments" eyebrow="03 · Segment explorer" title="Where response is strongest"><Segments results={data.channel_results || {}} /></Section><Section id="why" eyebrow="04 · Why" title="Drivers, risks, and switch conditions"><Why results={data.channel_results || {}} /></Section><Section id="audit" eyebrow="05 · Audit" title="Data source and method boundary"><Audit data={data} state={state} /></Section><footer className="footer"><span>Generated from dashboard_data.json</span><span>Artifacts: {num(data.artifacts?.length || 0)}</span></footer><Drawer title="Artifacts" open={drawer === 'artifacts'} onClose={() => setDrawer(null)}><DrawerList items={data.artifacts || []} /></Drawer><Drawer title="Run history" open={drawer === 'history'} onClose={() => setDrawer(null)}><DrawerList items={data.run_history?.steps || []} /></Drawer></main>;
}
